package com.dwd.dao;

import com.dwd.pojo.BookUser;

public interface BookUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_user
     *
     * @mbg.generated
     */
    int insert(BookUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_user
     *
     * @mbg.generated
     */
    int insertSelective(BookUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_user
     *
     * @mbg.generated
     */
    BookUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookUser record);
}